#pragma config(StandardModel, "Autopilot Robot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


float get_angle(int off_x,float distance)
{
	// in this case distance will be hypotenuse so we can find angle using this
	return (asin(off_x/distance)/3.14)*180;
}

float get_distance(int off_x,int off_y)
{
	return sqrt(off_x*off_x + off_y*off_y);
}


void rotate(float angle)
{
	resetGyro(gyroSensor);

	// left
	if(angle < 0)
	{
		while(angle < getGyroDegrees(gyroSensor))
		{
			setMotorSpeed(leftMotor,50);
			setMotorSpeed(rightMotor,-50);
		}
	}
	// right
	if(angle > 0)
	{
		while(angle < getGyroDegrees(gyroSensor))
		{
			setMotorSpeed(leftMotor,-50);
			setMotorSpeed(rightMotor,50);
		}
	}

}

void move(float distance)
{
	resetMotorEncoder(leftMotor);

	while(getMotorEncoder(leftMotor)<360*(distance/63*3.14))
	{
		setMultipleMotors(50,leftMotor,rightMotor);
	}
}

float move_to_next_coord(int c_x,int c_y,int n_x,int n_y,float r_angle)
{
	// get offset of current coord and next
	int off_x = n_x - c_x;
	int off_y = n_y - c_y;

	float distance = get_distance(off_x,off_y);

	// turn the robot in the direction to next coord
	float angle = get_angle(off_x,distance);
	angle = (angle <0) ? angle + r_angle : angle - r_angle;

	rotate(-angle);// vex angle are not correct

	r_angle = angle; // change angle of robot

	move(distance);	// move the robot to next coord
	return r_angle;
}


task main()
{
	float r_angle = 0;

	r_angle = move_to_next_coord(0,0,0,20,r_angle);

	r_angle = move_to_next_coord(0,20,10,20,r_angle);
	//playSound(soundGarageDoorClose);
	r_angle = move_to_next_coord(10,20,20,40,r_angle);
	//playSound(soundGarageDoorClose);


	r_angle = move_to_next_coord(10,40,10,10,r_angle);
}
